### ISSUE TITLE
Planner fails to launch when updating to 3.5.1

### ISSUE THREAD

**Issue by Spikey5** [ThizThizzyDizzy/nc-reactor-generator#68]
I haven't used the planner for a while but I received the update prompt on startup and agreed.
Previous version was 2.13.1 and the new jar downloaded into the existing directory but failed to launch.

I saw a similar issue and tried to run from the command line using the `java -jar` command and I got this output:

Initializing...
OS: Windows
OS Architecture: x64
Checking Libraries...
Checking... 5% (1/19)
Checking... 11% (2/19)
Checking... 16% (3/19)
Checking... 21% (4/19)
Checking... 26% (5/19)
Checking... 32% (6/19)
Checking... 37% (7/19)
Checking... 42% (8/19)
Checking... 47% (9/19)
Checking... 53% (10/19)
Checking... 58% (11/19)
Checking... 63% (12/19)
Checking... 68% (13/19)
Checking... 74% (14/19)
Checking... 79% (15/19)
Checking... 84% (16/19)
Checking... 89% (17/19)
Checking... 95% (18/19)
Checking... 100% (19/19)
Libraries OK
Initializing...
Exception in thread "main" java.lang.NoClassDefFoundError: org/lwjgl/system/CustomBuffer
        at planner.Main.main(Main.java:77)
Caused by: java.lang.ClassNotFoundException: org.lwjgl.system.CustomBuffer
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 1 more

However, I did manage to get it to run by moving to a new empty folder.
So this is more of a notification than anything.

Hope this helps!

**Comment by ThizThizzyDizzy** [comment]
This is caused by having old versions of some libraries (probably LWJGL); clearing the libraries folder will let it download the right versions and run properly

**Comment by ThizThizzyDizzy** [comment]
Fixed in v4.0
